name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  get_pr_commit_message:
    runs-on: ubuntu-20.04
    steps:
      - name: Determine if this is a pull request
        run: |
          if ["${{github.event_name}}" == "pull_request"]; then
            echo "This is a pull request event."
            echo "IS_PULL_REQUEST=true" >> $GITHUB_ENV
            echo "LATEST_LINK=${{toJson(github.event.pull_request._links.commits.href)}}" >> $GITHUB_ENV
          else
            echo "This is not a pull request event."
            echo "IS_PULL_REQUEST=false" >> $GITHUB_ENV
          fi

      - name: Print the IS_PULL_REQUEST variable
        run: echo "IS_PULL_REQUEST=$IS_PULL_REQUEST" echo "LATEST_LINK=$LATEST_LINK"

      - name: Conditional step based on IS_PULL_REQUEST
        if: ${{ env.IS_PULL_REQUEST == 'true' }}
        run: |
          echo "This step runs only for pull request events." 
          echo "CONTENT=$(curl -s -H "Accept: application/vnd.github.v3+json" $LATEST_LINK | jq '.[0].commit.message')"
          echo "Fetched content: $CONTENT"
          echo "CONTENT=${CONTENT}" >> $GITHUB_ENV

  deployment_pipeline:
    runs-on: ubuntu-20.04
    needs: [get_pr_commit_message]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: npm install success!
        if: ${{success()}}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: "info"
          description: "npm install successful"
          username: "Github Actions Bot"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK}}
      - name: npm install failure!
        if: ${{failure()}}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: "error"
          description: "npm install unsuccessful"
          details: "Please check the github actions logs for more information"
          username: "Github Actions Bot"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Check style
        run: npm run lint
      - name: Linting success!
        if: ${{success()}}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: "info"
          description: "Linting was successful"
          username: "Github Actions Bot"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Linting failure!
        if: ${{failure()}}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: "error"
          description: "Linting was unsuccessful"
          details: "Please check the github actions logs for more information"
          username: "Github Actions Bot"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Build
        run: npm run build
      - name: Build success!
        if: ${{success()}}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: "info"
          description: "Build was successful"
          username: "Github Actions Bot"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Build failure!
        if: ${{failure()}}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: "error"
          description: "Build was unsuccessful"
          details: "Please check the github actions logs for more information"
          username: "Github Actions Bot"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Run tests
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: npm test
      - name: Tests success!
        if: ${{success()}}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: "info"
          description: "Tests were successful"
          username: "Github Actions Bot"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Tests failure!
        if: ${{failure()}}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: "error"
          description: "Tests were unsuccessful"
          username: "Github Actions Bot"
          details: "Please check the github actions logs for more information"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Render Deployment
        if: ${{ github.event_name == 'push'}}
        uses: sws2apps/render-deployment@v1.7.0
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
      - name: Render deployment success!
        if: ${{success()}}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: "info"
          description: "Deployment was successful"
          username: "Github Actions Bot"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Render deployment failure!
        if: ${{failure()}}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: "error"
          description: "Deployment was unsuccessful"
          details: "Please check the github actions logs for more information"
          username: "Github Actions Bot"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
